##01. create service account
kubectl apply -f 2.1-federation-remote-sa.yaml

##02. describe service account
kubectl describe serviceaccounts tigera-federation-remote-cluster -n kube-system

##03. retrieve the token of the service account
kubectl describe secrets tigera-federation-remote-cluster-token-2k7r9 -n kube-system

##04. create secret from remote cluster kube-config
kubectl create secret generic remote-cluster-secret-uc-aks-prod-01 -n calico-system \
    --from-literal=datastoreType=kubernetes \
    --from-file=kubeconfig=../1-uc-aks-prod-01/1.2-kubeconfig-uc-aks-prod-01.yaml

##05. create RBAC for secret
kubectl apply -f 2.3-rbac.yaml

##06. remote cluster configuration
kubectl apply -f 2.4-remoteclusterconfiguration.yaml

##07 apply rbac for tigera-federation-remote-cluster sa
kubectl apply -f 2.5-rbac-sa.yaml
