apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: bookinfo
  annotations:
    federation.tigera.io/serviceSelector: app == "ratings"
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
  type: ClusterIP
